# Validation to help advance PR-#128, will be removed
name: Validation
permissions:
  contents: read

on:
  pull_request:

jobs:
  requires-integration-tests:
    uses: bikeindex/bike_index_ios/.github/workflows/integrationf.yml

  build-release:
    name: Workflow Validation
    runs-on: macos-26
    needs: requires-integration-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Ready
        run: echo "Ready!"
